name: Deploy to DigitalOcean Droplet
"on":
  push:
    branches:
      - samueltest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            cd /home/codes/inventario_front
            git pull origin samueltest
            npm run build
            pm2 restart front
            echo 'Deployment to digital ocean finished'
